### ISSUE TITLE
almost perfect picture sr.py

### ISSUE THREAD

**Issue by raialvaro** [remicres/sr4rs#20]
Hi Remi!

Thanks for all the advice you have given me. They have been very helpful!

**LR**
![image](https://user-images.githubusercontent.com/71493478/112952910-4b762a80-913d-11eb-98d8-89f04bd96a0d.png)

**HR**
![image](https://user-images.githubusercontent.com/71493478/112952959-55982900-913d-11eb-90f4-bbd539397fe2.png)

**SR**
![image](https://user-images.githubusercontent.com/71493478/112953003-621c8180-913d-11eb-83cf-0bfc0f173a27.png)

I recognize that the improvement has been great, thank you. The roads are better noticeable than in the LR image but there are something that worries me.

The buildings still have not finished creating them well and in the image it seems that there are grains or image distortion, as I show in the following image HR y SR

![image](https://user-images.githubusercontent.com/71493478/112953985-42398d80-913e-11eb-9a0d-42b5acf09164.png)

Could it be that you need more patches to train or do you need to change any parameters? or even do as in your job to lower Sentinel to 1.5 m?

Thanks for your help.

**Comment by remicres** [comment]
Hi @raialvaro ,

It's not easy to tell.
A wild guess is that these undesired artifacts might be caused by the VGG loss, which might be too high (compared to the other losses).
But I think that, since you have a small number of patches: you must perform more epochs. Your model might not be completely trained. Give a try: just restart a few hundreds epochs from the last checkpoint (use the `--load_ckpt` parameter to reload the model you already have trained) and see if the preview image in Tensorboard becomes nicer. 

Regarding losses weight tuning.
When you have to play with those weights: there is no absolute rule!
But here are some (over)simplified meanings of losses:

- **L1/L2** loss: radiometric accuracy. Too much weight: over-smoothed images. Not enough weight: no radiometric accuracy (and also sometimes the GAN do not converge to plausible images).
- **VGG** loss: helps with local details. Too much weight: some artifacts might appear (Most likely kind of "fish scales" pattern, as in your image) also lower radiometric accuracy. 

When (VGG loss + L1/L2 loss) is too low, GAN becomes too wild and creates plausible but nightmarish images. When it is too high, it can cause some artifacts in images (mostly from VGG loss) or over-smoothed images (due to L1/L2 loss)
