### ISSUE TITLE
Query related to Patches Extraction

### ISSUE THREAD

**Issue by HinalbPatel23** [remicres/sr4rs#79]
Hii,

I am trying to make 32x32 patches of  LR image (5m resolution) and 128x128 patches of HR image (1.25m resolution) using patches extraction .I am getting different number of patches of LR image and HR image.  can you please guide me why its happening and  how can i see which samples are rejected and why??

**Comment by remicres** [comment]
Hi @HinalbPatel23 ,

You must use the `OTB_TF_NBSOURCES` environment variable to tell `PatchesExtraction` to use two sources. This way it ensures that the same number of patches for each source is gathered. Also use the `sourceX.nodata` to set a value for no-data pixels, so that incomplete patches can be rejected.
